### PR TITLE
Bump to Smack 4.1.2

### PR DESCRIPTION
**Pull request by Flowdalic**
See https://github.com/kontalk/client-common-java/pull/8

### CODE REVIEW

**Comment by daniele-athome** [comment]
Thanks!!! @abika will review the changes and merge them.

**Comment by abika** [comment]
well thanks! But have you seen 0c5788945853a4e92a2b8a11c064e3494a7aebda ? I already tried upgrading to 4.1 but there is still the problem from https://community.igniterealtime.org/thread/55771 :
```
Jun 24, 2015 4:27:40 PM org.kontalk.client.Client connectAsync
WARNING: can't login
org.jivesoftware.smack.SmackException: No anonymous SASL authentication mechanism available
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginAnonymously(XMPPTCPConnection.java:439)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:403)
        at org.kontalk.client.Client.connectAsync(Client.java:169)
        at org.kontalk.client.Client.run(Client.java:350)
        at java.lang.Thread.run(Thread.java:745)
```

Can't merge when connection is not possible anymore .(

**Comment by Flowdalic** [comment]
> But have you seen 0c57889 ?

In fact now. A quick look shows that both a very similar, Mine has the advantage that it fetches the smack version from client-common-java.

> org.jivesoftware.smack.SmackException: No anonymous SASL authentication mechanism available

Are you sure that this is https://community.igniterealtime.org/thread/55771 and SMACK-670? Both describe a exception saying `java.lang.IllegalArgumentException: SASL authenticationText must not be null or empty (RFC6120 6.4.2)`. But I can bump to 4.1.2-SNAPSHOT for testing purposes. Then we'll see if it fixes the issue.

**Comment by abika** [comment]
>In fact not. A quick look shows that both a very similar, Mine has the advantage that it fetches the smack version from client-common-java.

Yeah no problem, we can take your version
> And are you sure that you need sync listeners?

No, but I wasn't sure about thread safety and wanted a quick, working solution. What was the default before, sync or async?

> Are you sure that this is https://community.igniterealtime.org/thread/55771 and SMACK-670?

Pretty sure. Error matches, time of code change matches, and I found the bug in `SASLMechanism` myself, although I didn't try fixing it. Would be cool, if you can check for 4.1.2.

**Comment by Flowdalic** [comment]
I'll release Smack 4.1.2 tomorrow.

**Comment by Flowdalic** [comment]
Bump to 4.1.2 (should be merged after https://github.com/kontalk/client-common-java/pull/9 has been merged).

**Comment by abika** [comment]
Thanks @Flowdalic ! (Login is working)

**Comment by Flowdalic** [comment]
yeah \o/

**Pull request merged**
