### PR TITLE
Add link to debian package

### PR DESCRIPTION
**Pull request by syamgk**
created a deb package for easy installation

### CODE REVIEW

**Comment by abika** [comment]
Thanks for your effort, but I simply can't add a link to an official page for a file I can't verify myself. Hope, you understand that.

But you should write to kontalk-devel@googlegroups.com about that, 	probably those folks are happy to hear about a Debian package.

**Comment by daniele-athome** [comment]
@syamgk you should provide source control files needed to build the package. That we can merge (we'll host the deb ourselves).

**Comment by syamgk** [comment]
Hosted the packages here.
http://128.199.69.92/kontalk

**Comment by daniele-athome** [comment]
@syamgk I was talking about the control files needed to dpkg-buildpackage to build the package. If you can provide us that we can merge those. We will take care of hosting then.

**Comment by syamgk** [comment]
add below line to /etc/apt/sources.list

    deb-src http://128.199.69.92/kontalk unstable main
apt-get update
apt-get source kontalk
**or**

    dget http://128.199.69.92/kontalk/pool/main/k/kontalk/kontalk_3.0.1%2bgit.20150725.affa0726-1.dsc

we are still improving the package

**Comment by daniele-athome** [comment]
Ok thanks, please provide the control files by using a pull request when you've finished.

**Comment by syamgk** [comment]
can you add options in gradle to use system jars?
in debian the jar files are in /usr/share/java
we want to package the dependencies which are not in debian.

**Comment by syamgk** [comment]
we want to maintain the packaging inside debian-java team

**Comment by pravi** [comment]
@daniele-athome all java packages in debian are maintained as a team and uses debian's git hosting service https://alioth.debian.org/projects/pkg-java/

I think it would be better to keep the packaging work there like all other java packaging.

**Comment by pravi** [comment]
Packaging files for all the existing java team maintained packages are here http://anonscm.debian.org/cgit/pkg-java/ We'd like to add kontalk there.

**Comment by pravi** [comment]
distribution should be jessie instead of unstable in sources.list (he has added a domain too)

    deb-src http://sgk01.tk/kontalk jessie main

**Pull request closed without merging**
