### PR TITLE
make java 8 the default as source and target platform

### PR DESCRIPTION
**Pull request by hennr**

### CODE REVIEW

**Comment by abika** [comment]
any explanation please? The reason for having set this to 1.7 is that a notification window will pop up if the application is started under Java 7 - the user is asked to update to Java 8.

**Comment by hennr** [comment]
Ah, didn't know this feature.
I just found it inconvinient that my IDE defaulted to 7 instead of 8 and didn't know exception multi catch and such. Also the README.md says java 8 is needed.

Your choice then.

**Comment by abika** [comment]
well, the README is correct, 8 is needed. I added a note the FAQs.

But yes, I'm missing features like lambdas and stream API. Java 7 is deprecated for a long time now, the switch to 1.8 will come eventually. I'll leave this open until then.

**Comment by hennr** [comment]
All right

**Comment by hennr** [comment]
Sorry @abika I made this pull request on my master branch which leaves the commit there locally and complicates merging upstream if you don't merge it.
I will close this PR because of that. Should I open an issue then or are you fine the way it is?

**Comment by abika** [comment]
no its fine. I won't forget it

**Pull request closed without merging**
